// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataUIClient is the client API for DataUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataUIClient interface {
	// ListEngineSpecs returns a list of Data Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DataUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type dataUIClient struct {
	cc grpc.ClientConnInterface
}

func NewDataUIClient(cc grpc.ClientConnInterface) DataUIClient {
	return &dataUIClient{cc}
}

func (c *dataUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (DataUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &DataUI_ServiceDesc.Streams[0], "/v1.DataUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DataUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type dataUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *dataUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dataUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.DataUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataUIServer is the server API for DataUI service.
// All implementations must embed UnimplementedDataUIServer
// for forward compatibility
type DataUIServer interface {
	// ListEngineSpecs returns a list of Data Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, DataUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedDataUIServer()
}

// UnimplementedDataUIServer must be embedded to have forward compatible implementations.
type UnimplementedDataUIServer struct {
}

func (UnimplementedDataUIServer) ListEngineSpecs(*ListEngineSpecsRequest, DataUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedDataUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedDataUIServer) mustEmbedUnimplementedDataUIServer() {}

// UnsafeDataUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataUIServer will
// result in compilation errors.
type UnsafeDataUIServer interface {
	mustEmbedUnimplementedDataUIServer()
}

func RegisterDataUIServer(s grpc.ServiceRegistrar, srv DataUIServer) {
	s.RegisterService(&DataUI_ServiceDesc, srv)
}

func _DataUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataUIServer).ListEngineSpecs(m, &dataUIListEngineSpecsServer{stream})
}

type DataUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type dataUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *dataUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _DataUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DataUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataUI_ServiceDesc is the grpc.ServiceDesc for DataUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DataUI",
	HandlerType: (*DataUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _DataUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _DataUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data-ui.proto",
}
